---
- set_fact:
    csgoserver_config: '{{ gameserver_config["csgoserver_config"] }}'
- name: "Configure source server"
  template:
    src: "csgoserver.cfg.j2"
    dest: "{{ gameserver_home }}/serverfiles/csgo/cfg/csgoserver.cfg"
